server:
  port: 9080
debug: true
spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/a2c?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: chen1997
    initialize: true
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis: 5000"
    #useGlobalDataSourceStat: true
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp"

mybatis:
  type-aliases-package: com.studycandy.a2c.model
  mapper-locations: classpath*:com/studycandy/a2c/mapper/*.xml

jdbc:
  prefix: s_a2c_

logging:
  level: debug